servo_ids: [0,1,2,3]
servo_type: 'RX'
servo_port: '/dev/ttyUSB0'
openhand_type: 'Model_O'
direction: [1,1,1,1]
poses:
  open:
    positions: [0.5, 0, 0, 0]
  power_sphere:
    positions: [0.5, 0.7, 0.7, 0.7]
  power_cylinder:
    positions: [1, 0.8, 0.8, 0.7]
  pinch:
    positions: [0, 0.9, 0.9, 0]
